### ISSUE TITLE
Fix support for the "All Blocks Test" Page

### ISSUE THREAD

**Issue by sHermanGriffiths** [innolitics/n2y#67]
Pandoc throws an error when parsing this page, which holds an example of each block. The error code is displayed below, nail down its source and correct it.

```
2022-08-31 13:41:59,826 - ERROR: Pandoc couldn't parse the generated AST. This is likely due to a bug in n2y or a plugin: JSON parse error: Error in $.blocks[1][0][0]: parsing Text failed, expected String, but encountered Null

Traceback (most recent call last):
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/utils.py", line 74, in pandoc_write_or_log_errors
    return pandoc.write(pandoc_ast, format=format, options=options)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/pandoc/__init__.py", line 337, in write
    pandoc(options)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/commands/base.py", line 99, in __call__
    return self.run(args, **kwargs)[1]
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/commands/processes.py", line 322, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/commands/processes.py", line 24, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/plumbum/machines/base.py", line 28, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 64
Command line: | /usr/local/bin/pandoc -t gfm+tex_math_dollars+raw_attribute -o /var/folders/g7/jkmzx_3n753c2sdkz350pt1c0000gn/T/tmprj44d4zm/output --wrap none --eol lf -f json /var/folders/g7/jkmzx_3n753c2sdkz350pt1c0000gn/T/tmprj44d4zm/input.js
Stderr:       | JSON parse error: Error in $.blocks[1][0][0]: parsing Text failed, expected String, but encountered Null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dcd/Coding/Innolitics/n2y/venv/bin/n2y", line 8, in <module>
    sys.exit(cli_main())
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/main.py", line 19, in cli_main
    sys.exit(main(args, access_token))
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/main.py", line 151, in main
    print(node.to_markdown())
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/page.py", line 111, in to_markdown
    self.content_to_markdown() or '',
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/page.py", line 100, in content_to_markdown
    return pandoc_ast_to_markdown(pandoc_ast)
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/utils.py", line 53, in pandoc_ast_to_markdown
    return pandoc_write_or_log_errors(
  File "/Users/dcd/Coding/Innolitics/n2y/venv/lib/python3.9/site-packages/n2y/utils.py", line 88, in pandoc_write_or_log_errors
    raise PandocASTParseError(msg)
n2y.errors.PandocASTParseError: Pandoc couldn't parse the generated AST. This is likely due to a bug in n2y or a plugin: JSON parse error: Error in $.blocks[1][0][0]: parsing Text failed, expected String, but encountered Null
```

**Comment by johndgiese** [comment]
@sHermanGriffiths can you confirm that this error occurred prior to your most recent changes?

**Comment by sHermanGriffiths** [comment]
Yes, that is true. This error was present on [this](https://github.com/innolitics/n2y/commit/76c802d7e2ed4ed4ae83a9353c2cb2c078bcf758) version
