### ISSUE TITLE
pandoc 2.5 error

### ISSUE THREAD

**Issue by hirisov** [innolitics/n2y#97]
Hello, 

I try to use this package under Linux Mint were the pandoc package is at version 2.5:

```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
````
It gives the following error:

```
Traceback (most recent call last):
  File "/home/xxx/.local/bin/n2y", line 5, in <module>
    from n2y.main import cli_main
  File "/home/xxx/.local/lib/python3.8/site-packages/n2y/main.py", line 7, in <module>
    from n2y import notion
  File "/home/xxx/.local/lib/python3.8/site-packages/n2y/notion.py", line 12, in <module>
    from n2y.page import Page
  File "/home/xxx/.local/lib/python3.8/site-packages/n2y/page.py", line 3, in <module>
    from .blocks import ChildDatabaseBlock, ChildPageBlock
  File "/home/xxx/.local/lib/python3.8/site-packages/n2y/blocks.py", line 5, in <module>
    from pandoc.types import (
ImportError: cannot import name 'TableHead' from 'pandoc.types' (/home/xxx/.local/lib/python3.8/site-packages/pandoc/types.py)
```

Any ideas please how to fix this?

**Comment by bimbashrestha** [comment]
Thanks for positing @hirisov!

I believe we've been using `pandoc 2.18` with `n2y` so far. I've seen similar errors in the past when I've tried running with a different `pandoc` version. Could you try downgrading and re-testing?

**Comment by hirisov** [comment]
Thanks for the hint @bimbashrestha ! I installed pandoc 2.18, and tried again. Now it didn't run into that error, it fetched all the content (I think) but then halted with a different error:

```
1.9.1.6.0.0.0.0.3.2.1 
1.9.1.7 Para([])
1.9.1.7.0 []
ERROR:n2y.utils:Pandoc couldn't parse the generated AST. This is likely due to a bug in n2y or a plugin: JSON parse error: Error in $.blocks[3]: key "t" not found

Traceback (most recent call last):
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/utils.py", line 76, in pandoc_write_or_log_errors
    return pandoc.write(pandoc_ast, format=format, options=options)
  File "/home/hirisov/.local/lib/python3.8/site-packages/pandoc/__init__.py", line 355, in write
    pandoc(options)
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/commands/processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/hirisov/.local/lib/python3.8/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 64
Command line: | /usr/bin/pandoc -t gfm+tex_math_dollars+raw_attribute -o /tmp/tmpsa396_j4/output --wrap none --eol lf -f json /tmp/tmpsa396_j4/input.js
Stderr:       | JSON parse error: Error in $.blocks[3]: key "t" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hirisov/.local/bin/n2y", line 8, in <module>
    sys.exit(cli_main())
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/main.py", line 18, in cli_main
    sys.exit(main(args, access_token))
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/main.py", line 81, in main
    export_completed = _export_node_from_config(client, export)
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/main.py", line 98, in _export_node_from_config
    result = export_page(
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/export.py", line 53, in export_page
    page_content = pandoc_write_or_log_errors(pandoc_ast, pandoc_format, pandoc_options)
  File "/home/hirisov/.local/lib/python3.8/site-packages/n2y/utils.py", line 90, in pandoc_write_or_log_errors
    raise PandocASTParseError(msg)
n2y.errors.PandocASTParseError: Pandoc couldn't parse the generated AST. This is likely due to a bug in n2y or a plugin: JSON parse error: Error in $.blocks[3]: key "t" not found
```
Any idea what can be the remedy for that one? :)

**Comment by bimbashrestha** [comment]
Hey @hirisov. Interesting.

Can you provide more details about how your got this error? Are you running n2y from the command line (if so, what was the command)? What do the contents of your Notion page look like?

**Comment by hirisov** [comment]
hello @bimbashrestha , sure I try. I use n2y v0.7.5 with pandoc 2.18 and tried the sample config from the docs:
```
exports:
- id: 9d962de.......................
  node_type: page
  output: page.md
```
And I ran

```
n2y configuration.yaml
```
My notion is nothing exotic, just pages, and some databases inside them. If there is anything else I can debug/test please tell me. Should I try to generate it for smaller subset of pages and try to find which one couses the error?
